import Vue from 'vue'
import { NavBar, Form, Field, Button, Tabbar, TabbarItem, Image as VanImage, Icon, Tab, Tabs, Cell, PullRefresh, List, Lazyload, ActionSheet, Popup, Col, Row, Badge, Search, Divider } from 'vant'

Vue.use(Search)
Vue.use(Badge)
Vue.use(Col)
Vue.use(Row)
Vue.use(Popup)
Vue.use(ActionSheet)
Vue.use(Lazyload)
Vue.use(List)
Vue.use(PullRefresh)
Vue.use(Cell)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Field)
Vue.use(Form)
Vue.use(NavBar)
Vue.use(Button)
Vue.use(VanImage)
Vue.use(Icon)
Vue.use(Divider)
